# Generated by Django 4.2.16 on 2024-11-22 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='age',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='game',
            name='age_limited',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.TextField(),
        ),
    ]
