# Generated by Django 4.2.16 on 2024-11-22 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0002_alter_buyer_age_alter_game_age_limited_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='age_limited',
            field=models.BooleanField(default='False'),
        ),
    ]
